export default {
    primary: '#474747',
    primaryBackground: '#FFF',
    colorWhite: '#FFF',
    colorBlue: '#0badde',
    colorBlueLight: '#cdf3ff',
    colorBlueLighter: '#f5fcfe',
    colorPinkDark: '#cc517a',
    colorPink: '#f0bdd0',
    colorGreyDark: '#474747',
    colorGrey: '#bdc8cc',
    colorOrangeDark: '#ff390d',
    colorGreen: '#95c11f',
    colorBrownLight: '#c1b3b7',
}